# 5.2.1 Ensure sudo is installed
- name: Ensure sudo is installed
  ansible.builtin.package:
    name: sudo
    state: present

# 5.2.2 Ensure sudo commands use pty
- name: Ensure sudo commands use pty
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^#?Defaults\s+use_pty'
    line: "Defaults use_pty"

# 5.2.3 Ensure sudo log file exists
- name: Ensure sudo log file exists
  when: cis_Stage > 1
  block:
    - name: Ensure sudo log directory exists
      ansible.builtin.file:
        path: /var/log/sudo
        state: directory
        owner: root
        group: root
        mode: '0750'

    - ansible.builtin.file:
        path: /var/log/sudo/sudo.log
        state: touch
        owner: root
        group: root
        mode: '0640'

    - name: Ensure sudo commands use pty
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^#?Defaults\s+logfile', line: 'Defaults logfile="/var/log/sudo/sudo.log"' }


# 5.2.4 Ensure users must provide password for privilege escalation
# 5.2.5 Ensure re-authentication for privilege escalation is not disabled globally
- name: Remove lines with NOPASSWD tags in sudoers file
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "{{ item.regexp }}"
  with_items:
    - { regexp: '^.*NOPASSWD.*$'}
    - { regexp: '^Defaults\s+!authenticate'}

# 5.2.6 Ensure sudo authentication timeout is configured correctly
- name: Ensure sudo authentication timeout is configured correctly
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^Defaults\s+timestamp_timeout=', line: 'Defaults timestamp_timeout={{ sudo_timeout }}' }

# Need change
# 5.2.7 Ensure access to the su command is restricted
- name: Restrict su command to wheel group
  ansible.builtin.lineinfile:
    path: /etc/pam.d/su
    state: present
    regexp: '^#?auth\s+required\s+pam_wheel.so\s+use_uid'
    line: 'auth required pam_wheel.so use_uid group=sugroup'
