---

- name: install auditd package
  package:
    name: '{{ audit_package }}'
    state: 'present'

- name: configure auditd
  template:
    src: 'audit.conf.j2'
    dest: '/etc/audit/audit.conf'
    owner: 'root'
    group: 'root'
    mode: '0640'

- name: to collect login and logout events
  template:
    src: 'audit.rules'
    dest: '/etc/audit/rules.d/audit.rules'
    owner: 'root'
    group: 'root'
    mode: '0640'
