---
# 6.3.1 Ensure AIDE is installed
- name: Install & Configure aide
  when: ansible_os_family == "Debian"
  block:
    - name: Install aide
      ansible.builtin.apt:
        name:
          - aide
          - aide-common
        state: "present"
      register: "aide_installed"
      until: "aide_installed is succeeded"

    - name: "Configure aide"
      ansible.builtin.shell: aideinit
      args:
        creates: "/var/lib/aide/aide.db"

    - name: Copy the newly generated database
      ansible.builtin.copy:
        remote_src: true
        src: "/var/lib/aide/aide.db.new"
        dest: "/var/lib/aide/aide.db"
      ignore_errors: true

    - name: Remove the newly generated database
      ansible.builtin.file:
        path: /var/lib/aide/aide.db.new
        state: absent

- name: Install & Configure aide "RedHat
  when: ansible_os_family == "RedHat"
  block:
    - name: Install aide
      ansible.builtin.yum:
        name: aide
        state: "present"
      register: "aide_installed"
      until: "aide_installed is succeeded"

    - name: Configure aide
      ansible.builtin.shell: aide --init
      args:
        creates: /var/lib/aide/aide.db.gz

    - name: Copy the newly generated database
      ansible.builtin.copy:
        remote_src: true
        src: "/var/lib/aide/aide.db.new.gz"
        dest: "/var/lib/aide/aide.db.gz"
      ignore_errors: true

    - name: Remove the newly generated database
      ansible.builtin.file:
        path: /var/lib/aide/aide.db.new.gz
        state: absent

# 6.1.2 Ensure filesystem integrity is regularly checked
- name: "Service files are copied"
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: '0644'
  with_items:
    - { src: aidecheck.service.j2, dest: /etc/systemd/system/aidecheck.service }
    - { src: aidecheck.timer, dest: /etc/systemd/system/aidecheck.timer }
  notify:
    - Reload AIDE
