- name: Temporarily set default policies to ACCEPT ({{ ipver }})
  ansible.builtin.iptables:
    table: filter
    chain: "{{ item }}"
    policy: ACCEPT
    ip_version: "{{ ipver }}"
  ignore_errors: true
  loop:
    - INPUT
    - FORWARD
    - OUTPUT

# Flush existing iptables chains
- name: Flush existing iptables rules ({{ ipver }})
  ansible.builtin.iptables:
    table: filter
    chain: "{{ item }}"
    flush: true
    ip_version: "{{ ipver }}"
  ignore_errors: true 
  loop:
    - INPUT
    - FORWARD
    - OUTPUT

# Loopback rules
- name: Allow loopback traffic ({{ ipver }})
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
    ip_version: "{{ ipver }}"

- name: Allow outbound loopback traffic ({{ ipver }})
  ansible.builtin.iptables:
    table: filter
    chain: OUTPUT
    out_interface: lo
    jump: ACCEPT
    ip_version: "{{ ipver }}"

- name: Drop spoofed 127/8 packets  (ipv4 only)
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    source: 127.0.0.0/8
    jump: DROP
    ip_version: "ipv4"
  when: ipver == 'ipv4'

- name: Drop spoofed IPv6 loopback packets (::1) (ipv6 only)
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    source: ::1
    jump: DROP
    ip_version: ipv6
  when: ipver == 'ipv6'

# Allow established and related connections
- name: Allow established and related inbound ({{ ipver }})
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    ip_version: "{{ ipver }}"

- name: Allow established, related, and new outbound ({{ ipver }})
  ansible.builtin.iptables:
    table: filter
    chain: OUTPUT
    ctstate: NEW,ESTABLISHED,RELATED
    jump: ACCEPT
    ip_version: "{{ ipver }}"

# Allow inbound ports
- name: Allow inbound allowed ports ({{ ipver }})
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    protocol: "{{ item.proto }}"
    destination_port: "{{ item.port }}"
    jump: ACCEPT
    ip_version: "{{ ipver }}"
  loop: "{{ allowed_ports }}"
  when: allowed_ports | length > 0

# Allow outbound ports
- name: Allow outbound allowed ports ({{ ipver }})
  ansible.builtin.iptables:
    table: filter
    chain: OUTPUT
    protocol: "{{ item.proto }}"
    destination_port: "{{ item.port }}"
    jump: ACCEPT
    ip_version: "{{ ipver }}"
  loop: "{{ allowed_ports }}"
  when: allowed_ports | length > 0

# Default DROP policies
- name: Set default policies ({{ ipver }})
  ansible.builtin.iptables:
    table: filter
    chain: "{{ item.chain }}"
    policy: "{{ item.policy }}"
    ip_version: "{{ ipver }}"
  loop:
    - { chain: INPUT, policy: DROP }
    - { chain: FORWARD, policy: DROP }
    - { chain: OUTPUT, policy: DROP }
