---
# Ensure cron daemon is enabled and active
- name: Ensure cron daemon is enabled and active
  ansible.builtin.systemd:
    name: "{{ cron_service }}"
    masked: no
    enabled: true
    state: started
  become: true

# Ensure permissions on cron directories are configured
- name: Ensure permissions on cron directories are configured
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '0700'
  loop: "{{ cron_dirs }}"
  become: true

# Ensure permissions on /etc/crontab are configured
- name: Ensure permissions on crontab file
  ansible.builtin.file:
    path: "{{ cron_tab_file }}"
    owner: root
    group: root
    mode: '0600'
  become: true

# Ensure /etc/cron.allow exists and is properly secured
- name: Ensure /etc/cron.allow exists and is secured
  ansible.builtin.file:
    path: "{{ cron_allow_file }}"
    state: touch
    owner: root
    group: root
    mode: '0640'
  become: true

# Check if /etc/cron.deny exists
- name: Check if /etc/cron.deny exists
  ansible.builtin.stat:
    path: "{{ cron_deny_file }}"
  register: cron_deny_status

# Ensure /etc/cron.deny permissions if file exists
- name: Ensure /etc/cron.deny permissions if exists
  ansible.builtin.file:
    path: "{{ cron_deny_file }}"
    owner: root
    group: root
    mode: '0640'
  when: cron_deny_status.stat.exists
  become: true

