---


####################################################
###### Configure System Logging ######
####################################################
- name: Ensure filesystem integrity is regularly checked
  include_tasks: filesystem_Integrity.yaml
  when: cis_Stage > 1

- name: Configure System files
  include_tasks: system_file_permissions.yaml
