---
# Ensure iptables, and firewalld are installed
- name: "Ensure iptables, and firewalld are installed"
  become: true
  ansible.builtin.package:
    name: "{{ firewall_base_packages }}"
    state: present

# Ensure a single firewall configuration utility is in use
- name: Ensure only one firewall configuration utility is active
  block:

    - name: Gather installed firewall packages
      ansible.builtin.package_facts:
        manager: auto

    - name: Get list of all systemd service units
      ansible.builtin.command: systemctl list-unit-files --type=service --no-legend --no-pager
      register: systemd_units
      changed_when: false
      failed_when: false

    - name: Get active firewall services
      ansible.builtin.shell: |
        systemctl list-units --type=service --state=active | grep -E 'firewalld|nftables|iptables' | awk '{print $1}'
      register: active_firewall_services
      changed_when: false
      failed_when: false

    - name: Configure Firewalld as active firewall
      when: "'firewalld' in ansible_facts.packages"
      block:
        - name: Remove conflicting packages for Firewalld
          ansible.builtin.package:
            name: "{{ firewall_remove_packages.firewalld }}"
            state: absent
          ignore_errors: true

        - name: Stop and mask nftables and iptables
          ansible.builtin.systemd:
            name: "{{ item }}"
            state: stopped
            masked: true
          loop: "{{ firewall_stop_services.firewalld }}"
          when: item + '.service' in systemd_units.stdout

    - name: Configure NFTables as active firewall
      when: "'nftables' in ansible_facts.packages and 'firewalld' not in ansible_facts.packages"
      block:
        - name: Remove conflicting packages for NFTables
          ansible.builtin.package:
            name: "{{ firewall_remove_packages.nftables }}"
            state: absent
          ignore_errors: true

        - name: Stop and mask firewalld and iptables
          ansible.builtin.systemd:
            name: "{{ item }}"
            state: stopped
            masked: true
          loop: "{{ firewall_stop_services.nftables }}"
          when: item + '.service' in systemd_units.stdout

    - name: Configure IPTables as active firewall
      when: "'iptables-services' in ansible_facts.packages and 'firewalld' not in ansible_facts.packages and 'nftables' not in ansible_facts.packages"
      block:
        - name: Remove conflicting packages for IPTables
          ansible.builtin.package:
            name: "{{ firewall_remove_packages['iptables-services'] }}"
            state: absent
          ignore_errors: true

        - name: Stop and mask firewalld and nftables
          ansible.builtin.systemd:
            name: "{{ item }}"
            state: stopped
            masked: true
          loop: "{{ firewall_stop_services['iptables-services'] }}"
          when: item + '.service' in systemd_units.stdout

# Ensure firewalld service is enabled and running
- name: Ensure firewalld service is enabled and running
  become: true
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    masked: false
    state: started
  when: "'firewalld' in ansible_facts.packages"

