---
# Ensure insecure service clients are not installed 
- name: "Ensure insecure service clients are not installed"
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop:
    - ftp      # Ensure FTP client is not installed
    - ypbind   # Ensure NIS client is not installed
    - telnet   # Ensure Telnet client is not installed
    - tftp     # Ensure TFTP client is not installed
  become: true

