---
# Kernel hardening parameters
- name: "Configure kernel hardening parameters"
  ansible.builtin.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
    reload: yes
    sysctl_file: /etc/sysctl.d/60-kernel_sysctl.conf
  loop: "{{ kernel_hardening_params }}"
  loop_control:
    label: "{{ item.desc }}"

# Core dump restrictions
- name: "Configure core dump restrictions"
  ansible.builtin.blockinfile:
    path: /etc/systemd/coredump.conf
    create: yes
    block: "{{ item.block }}"
  loop: "{{ core_dump_blocks }}"
  loop_control:
    label: "{{ item.desc }}"
  notify:
    - reload systemd reexec

