# Ensure GPG keys are configured

- name: "Check for GPG keys in repo files"
  ansible.builtin.shell: "grep -r 'gpgkey' /etc/yum.repos.d/* || true"
  register: gpgkey_output
  changed_when: false

- name: "Fail if GPG key URL missing"
  ansible.builtin.fail:
    msg: "FAILED – Missing GPG key in one or more repositories!"
  when: gpgkey_output.stdout == ""

- name: "Import required GPG keys"
  ansible.builtin.rpm_key:
    state: present
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-linux-{{ ansible_distribution_major_version }}"
  notify: Yum_clean_metadata

# Ensure gpgcheck=1 globally

- name: Check if /etc/yum.conf exists
  become: true
  ansible.builtin.stat:
    path: /etc/yum.conf
  register: yum_conf_stat

- name: Find yum repo config files
  become: true
  ansible.builtin.find:
    paths: /etc/yum.repos.d
    patterns: "*.conf"
    file_type: file
  register: yum_config_d_files

- name: Build full rsyslog config file list
  ansible.builtin.set_fact:
    yum_config_all_files: >-
      {{
        (yum_conf_stat.stat.exists | ternary(['/etc/yum.conf'], []))
        + (yum_config_d_files.files | map(attribute='path') | list)
      }}

- name: "Ensure gpgcheck=1 in yum.conf"
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: '^gpgcheck\s*=.*'
    replace: 'gpgcheck=1'
  loop: "{{ yum_config_all_files }}"
  loop_control:
    label: "{{ item }}"
  notify: Yum_clean_all

# Ensure repo_gpgcheck=1 globally
- name: "Ensure repo_gpgcheck=1 in yum.conf"
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: '^repo_gpgcheck\s*=.*'
    replace: 'repo_gpgcheck=1'
  loop: "{{ yum_config_all_files }}"
  loop_control:
    label: "{{ item }}"
  notify: Yum_clean_metadata

# Ensure package manager repositories are configured
- name: "Check if repos are configured"
  ansible.builtin.command: yum repolist enabled
  register: repo_status
  changed_when: false

- name: "Fail if no repos configured"
  ansible.builtin.fail:
    msg: "FAILED – No yum repositories configured!"
  when: "'repolist: 0' in repo_status.stdout"

- name: "Check repo directory existence"
  ansible.builtin.stat:
    path: "/etc/yum.repos.d/"
  register: repodir

- name: "Fail if /etc/yum.repos.d is missing"
  ansible.builtin.fail:
    msg: "FAILED – /etc/yum.repos.d directory not found!"
  when: repodir.stat.exists == false

# Ensure updates, patches, and security software installed

- name: "Ensure all system packages are updated"
  ansible.builtin.yum:
    name: "*"
    state: latest
    update_cache: true
