---
- name: update cache
  apt:
    update_cache: true

# 1.1 Filesystem Configuration
- name: 1.1 Filesystem Configuration
  include_tasks: filesystem_Configuration.yaml

# 1.3 Filesystem Integrity Checking
- name: Ensure filesystem integrity is regularly checked
  include_tasks: filesystem_Integrity.yaml

# 1.4 Secure Boot Settings
- name: Secure Boot Settings
  include_tasks: secure_BootSettings.yaml

# 1.5 Additional Process Hardening
- name: Process Hardening
  include_tasks: process_Hardening.yaml

# 2.2 Special Purpose Services
- name: Remove Special Purpose Services
  apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ specialPurposeServices }}"

# 2.3 Service Clients
- name: Remove Service Clients
  apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ serviceClinetPackagesList }}"

# 4.1 Configure System Accounting (auditd)
- name: Configure System Accounting (auditd)
  include_tasks: audit.yaml
