---
- name: Amazon Linux 2 | Configure System Accounting (auditd) 
  include_tasks:  configure_system_accounting_al2.yaml
  
- name: Amazon Linux 2 | Configure Host Based Firewall
  include_tasks: configure_host_based_firewall_al2.yaml

- name: Amazon Linux 2 | User Accounts and Environment
  include_tasks: user_accounts_and_environment_al2.yaml

- name: Amazon Linux 2 | User Accounts and Environment
  include_tasks: user_accounts_and_environment_al2.yaml

- name: Amazon Linux 2 | Local User and Group Settings
  include_tasks: local_user_and_group_settings_al2.yaml

- name: Amazon Linux 2 | Configure Logging (rsyslog + journald)
  include_tasks: configure_logging_al2.yaml

- name: Amazon Linux 2 | Configure Software and Patch Management
  include_tasks: configure_software_and_patch_management_al2.yaml
