---
###################################################
# 1.1.1 Configure Filesystems kernel modules #
###################################################
- name: Disable filesystem kernel modules
  ansible.builtin.blockinfile:
    path: "/etc/modprobe.d/{{ item }}.conf"
    block: |
      install {{ item }} /bin/true
      blacklist {{ item }}
    create: yes
  loop: >-
    {{
      (filesystem_kernel_modules.common | default([]))
      + (filesystem_kernel_modules.get(ansible_facts.os_family, []) | list)
    }}


########################################
# 1.1.2 Configure Filesystem Partition #
########################################

# Configure partitions for tmp directories

# ----------------------------------------------------------------------------- 
# 1. Check whether each path is **already** mounted as tmpfs with nodev,noexec,nosuid
# -----------------------------------------------------------------------------
- name: Check current mount options for secure tmpfs mounts
  ansible.builtin.shell: |
    mount | grep -E '^tmpfs on {{ item }} type tmpfs .*nodev.*noexec.*nosuid'
  loop:
    - /tmp
    - /dev/shm
  register: tmpfs_mount_check
  ignore_errors: true
  changed_when: false
  failed_when: false

# ----------------------------------------------------------------------------- 
# 2. Mount only the directories that **failed** the check above
# -----------------------------------------------------------------------------
- name: Mount directories as tmpfs with nodev, noexec, and nosuid options
  ansible.posix.mount:
    path: "{{ item }}"
    src:  tmpfs
    fstype: tmpfs
    opts: nodev,noexec,nosuid
    state: mounted
  loop:
    - /tmp
    - /dev/shm
  loop_control:
    index_var: idx
  when: tmpfs_mount_check.results[idx].rc != 0
  changed_when: false

- name: Ensure /tmp mount is enabled at boot
  ansible.builtin.systemd:
    name: tmp.mount
    enabled: true
  become: true
  loop_control:
    index_var: idx
  when: tmpfs_mount_check.results[idx].rc != 0

# - name: Bind mount directories with secure options
#   ansible.posix.mount:
#     path: "{{ item.path }}"
#     src: "{{ item.device }}"
#     fstype: none
#     opts: "{{ item.opts }}"
#     state: mounted
#   loop: "{{ dir_partition }}"

# Configure /home & /var partitions
- name: Mount directories with nodev and nosuid options
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.device }}"
    fstype: ext4
    opts: "{{ item.opts }}"
    state: mounted
  #changed_when: false
  loop: "{{ dir_partition }}"
