---
# 1.3.1 Ensure AIDE is installed
- name: "Ensure aide is installed"
  apt:
    name:
      - aide
      - aide-common
    state: "present"
  register: "aide_installed"
  until: "aide_installed is succeeded"
  when: ansible_os_family == "Debian"

- name: "Configure aide"
  shell: aideinit
  changed_when: false

- name: "copy the newly generated database"
  copy:
    remote_src: true
    src: "/var/lib/aide/aide.db.new"
    dest: "/var/lib/aide/aide.db"

# 1.3.2 Ensure filesystem integrity is regularly checked
- name: "Service files are copied"
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: '0644'
  with_items:
    - { src: aidecheck.service, dest: /etc/systemd/system/aidecheck.service }
    - { src: aidecheck.timer, dest: /etc/systemd/system/aidecheck.timer }
  notify:
    - Reload the services
