---
# Ensure sticky bit is set on all world-writable directories
- name: First Part
  shell: |
    set -o pipefail
    df --local -P | awk '{if (NR!=1) print $6}'
  args:
    executable: /bin/bash
  changed_when: true
  register: result_1

- name: Second Part
  shell: |
    set -o pipefail
    echo '{{ result_1.stdout }}' | xargs -I '{}' find '{}' -xdev -type d \( -perm -0002 -a ! -perm -1000 \) 2>/dev/null
  changed_when: true
  register: result_2
  args:
    executable: /bin/bash

- name: Third Part
  shell: |
    set -o pipefail
    echo '{{ result_2.stdout }}' | xargs -I '{}' chmod a+t '{}'
  changed_when: true
  register: result_3
  args:
    executable: /bin/bash

- name: Disable automounting
  service:
    name: autofs
    enabled: false
    state: stopped
  ignore_errors: true
  register: autofs_result
  failed_when: "autofs_result.failed and 'no service or tool found for: autofs' not in autofs_result.msg"
