# 4.1.1 Ensure a single firewall configuration utility is in use
- name: Uninstall non-selected firewall packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop: "{{ firewall_packages_by_os[ansible_facts.os_family] | default([]) }}"
  when: item != firewall_package

# 4 Ensure a single firewall is configured
- name: Install selected firewall package
  ansible.builtin.package:
    name:  "{{ firewall_package }}"
    state: present

- name: Ensure firewall_package service is enabled and started
  ansible.builtin.service:
    name: '{{ firewall_package }}'
    state: started
    enabled: true
  
# # 4.1 Cofigure ufw
- name: Configure ufw
  when: firewall_package == "ufw"
  block:
    - name: Ensure iptables-persistent absent
      ansible.builtin.apt:
        name: iptables-persistent
        state: absent

    - name: Unmask ufw service (if needed)
      ansible.builtin.systemd:
        name: ufw.service
        masked: false

    - name: Allow SSH through UFW
      community.general.ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Allow everything and enable UFW
      community.general.ufw:
        state: enabled

    - name: Ensure ufw loopback traffic is configured
      ansible.builtin.command: "{{ item }}"
      loop:
        - ufw allow in on lo
        - ufw allow out on lo
        - ufw deny in from 127.0.0.0/8
        - ufw deny in from ::1

    - name: Ensure ufw rules for specific ports
      community.general.ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      loop: "{{ allowed_ports }}"

  # 4.2.5 Ensure ufw outbound connections are configured (Manual)
  # - name: Ensure ufw outbound connections are configured
  #   command: ufw allow out on all

    - name: Set default deny incoming policy
      ufw:
        policy: deny
        direction: incoming

    - name: Set default deny outgoing policy
      ufw:
        policy: deny
        direction: outgoing
      when: "'22/tcp ALLOW' in ufw_status.stdout or '22 ALLOW' in ufw_status.stdout"
      vars:
        ufw_status: "{{ lookup('pipe', 'ufw status') | default('') }}"

    - name: Set default deny incoming policy
      ufw:
        policy: deny
        direction: routed

# 4.2 Cofigure nftables
- name: Configure nftables
  when: firewall_package == "nftables"
  block:
    - name: Ensure iptables are flushed before using nftables
      ansible.builtin.command: iptables -F
      ignore_errors: true

    - name: Ensure nftables configuration directory exists
      ansible.builtin.file:
        path: /etc/nftables
        state: directory
        mode: "0755"

    - name: Create nftables ruleset from template
      ansible.builtin.template:
        src: nftables.conf.j2
        dest: /etc/nftables/{{ nftable_name }}.conf
        owner: root
        group: root
        mode: "0644"

    - name: Ensure nftables main config includes our table
      ansible.builtin.lineinfile:
        path: /etc/nftables.conf
        regexp: '^include "/etc/nftables/{{ nftable_name }}.conf"'
        line: 'include "/etc/nftables/{{ nftable_name }}.conf"'
        insertafter: EOF
      notify: Apply nftables ruleset
    - name: Save nftables rules persistently
      ansible.builtin.command: "nft list ruleset > /etc/nftables.conf"

# 4.3 Cofigure iptables
- name: Configure iptables
  when: firewall_package == "iptables"
  block:
    - name: Ensure iptables-persistent is installed
      ansible.builtin.apt:
        name: iptables-persistent
        state: present
      become: true

    - name: Flush existing iptables rules
      ansible.builtin.command: iptables -F
      ignore_errors: true

    - name: Disabling and stoping NFTables
      ansible.builtin.service:
        name: 'nftables.service'
        state: stopped
        enabled: false

    - name: Disable UFW
      community.general.ufw:
       state: disabled
      ignore_errors: true
  
    - name: Check if nftables service exists
      ansible.builtin.shell: systemctl status nftables.service
      register: nftables_status
      failed_when: false
      changed_when: false
      become: true

    - name: Stop nftables service
      ansible.builtin.systemd:
        name: nftables
        state: stopped
        enabled: no
      when: nftables_status.rc == 0
      become: true
      ignore_errors: true

    - name: Mask nftables service
      ansible.builtin.systemd:
        name: nftables
        masked: yes
      when: nftables_status.rc == 0
      become: true
      ignore_errors: true

    - name: Ensure iptables configuration directory exists
      ansible.builtin.file:
        path: /etc/iptables
        state: directory
        mode: "0755"

    - name: Deploy IPv4 iptables template
      ansible.builtin.template:
        src: iptables.rules.v4.j2
        dest: /etc/iptables/rules.v4
        owner: root
        group: root
        mode: "0644"

    - name: Deploy IPv6 rules template
      ansible.builtin.template:
        src: iptables.rules.v6.j2
        dest: /etc/iptables/rules.v6
        owner: root
        group: root
        mode: "0644"

    - name: Apply IPv4 rules
      ansible.builtin.command: iptables-restore /etc/iptables/rules.v4
      become: true

    - name: Apply IPv6 rules
      ansible.builtin.command: ip6tables-restore /etc/iptables/rules.v6
      become: true

# 4.4 Configure firewalld
- name: Configure firewalld
  when: firewall_package == "firewalld"
  block:
    - name: Ensure firewalld default zone is set to 'public'
      ansible.posix.firewalld:
        zone: public
        state: enabled
        permanent: true

    - name: Allow required services
      ansible.posix.firewalld:
        service: "{{ item }}"
        zone: public
        permanent: true
        state: enabled
      loop: "{{ allowed_services }}"
      notify: Reload firewalld

    - name: Allow required ports
      ansible.posix.firewalld:
        port: "{{ item.port }}/{{ item.proto }}"
        zone: public
        permanent: true
        state: enabled
      loop: "{{ allowed_ports }}"
      notify: Reload firewalld

    # -------------------------------
    # Loopback traffic configuration
    # -------------------------------

    - name: Allow loopback traffic (IPv4/IPv6)
      ansible.posix.firewalld:
        rich_rule: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - 'rule family="ipv4" source address="127.0.0.0/8" accept'
        - 'rule family="ipv6" source address="::1" accept'
        - 'rule family="ipv4" source address="127.0.0.0/8" not interface="lo" drop'
        - 'rule family="ipv6" source address="::1" not interface="lo" drop'
      notify: Reload firewalld

    # -------------------------------
    # Drop all other inbound and forward traffic by default
    # -------------------------------

    - name: Set default zone target to DROP
      ansible.posix.firewalld:
        zone: public
        target: DROP
        permanent: true
      notify: Reload firewalld

  rescue:
    - name: Log error configuring firewalld
      ansible.builtin.debug:
        msg: "Firewalld configuration failed."
