# 4.1.1 Ensure a single firewall configuration utility is in use
- name: Uninstall non-selected firewall packages
  package:
    name: "{{ item }}"
    state: absent
  loop: "{{ firewall_packages_by_os[ansible_facts.os_family] | default([]) }}"
  when: item != firewall_package

# 4 Ensure a single firewall is configured
- name: Install selected firewall package
  package:
    name:  "{{ firewall_package }}"
    state: present

- name: Ensure iptables-persistent is not installed with ufw
  apt:
    name: iptables-persistent
    state: absent
  when: firewall_package == "ufw"

- name: Ensure firewall_package service is enabled and started
  systemd:
    name: '{{ firewall_package }}'
    enabled: yes
    state: started
  
# # 4.1 Cofigure ufw
- name: Configure ufw
  when: firewall_package == "ufw"
  block:
    - name: Unmask ufw service (if needed)
      ansible.builtin.systemd:
        name: ufw.service
        masked: false

    - name: Allow SSH through UFW
      ansible.builtin.command: ufw allow ssh

    - name: Allow everything and enable UFW
      community.general.ufw:
        state: enabled

    - name: Ensure ufw loopback traffic is configured
      command: '{{ item }}'
      with_items:
      - ufw allow in on lo
      - ufw allow out on lo
      - ufw deny in from 127.0.0.0/8
      - ufw deny in from ::1

  # 4.2.5 Ensure ufw outbound connections are configured (Manual)
  # - name: Ensure ufw outbound connections are configured
  #   command: ufw allow out on all

    - name: Ensure ufw rules for specific ports
      ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      with_items:
        - { port: "22", proto: "tcp" }
        - { port: "53", proto: "tcp" }
        - { port: "53", proto: "udp" }
        - { port: "80", proto: "tcp" }
        - { port: "443", proto: "tcp" }

    - name: Set default deny incoming policy
      ufw:
        policy: deny
        direction: incoming

    - name: Set default deny outgoing policy
      ufw:
        policy: deny
        direction: outgoing

    - name: Set default deny incoming policy
      ufw:
        policy: deny
        direction: routed

# 4.2 Cofigure nftables
- name: Configure nftables
  when: firewall_package == "nftables"
  block:
    - name: Check if nftables table exists
      command: nft list table inet nf_table
      register: nft_table_check
      changed_when: false
      failed_when: false

    - name: Create nftables ruleset from template
      template:
        src: nftables.conf.j2
        dest: /etc/nftables.conf
      notify: Apply nftables ruleset

# 4.3 Cofigure iptables
- name: Configure iptables
  when: firewall_package == "iptables"
  block:
    - name: Ensure iptables-persistent is installed
      ansible.builtin.apt:
        name: iptables-persistent
        state: present
      become: true

    - name: Disabling and stoping NFTables
      ansible.builtin.service:
        name: 'nftables.service'
        state: stopped
        enabled: false

    - name: Disable UFW
      community.general.ufw:
       state: disabled
      ignore_errors: true
  
    - name: Check if nftables service exists
      ansible.builtin.shell: systemctl status nftables.service
      register: nftables_status
      failed_when: false
      changed_when: false
      become: true

    - name: Stop nftables service
      ansible.builtin.systemd:
        name: nftables
        state: stopped
        enabled: no
      when: nftables_status.rc == 0
      become: true
      ignore_errors: true

    - name: Mask nftables service
      ansible.builtin.systemd:
        name: nftables
        masked: yes
      when: nftables_status.rc == 0
      become: true
      ignore_errors: true

    - name: Accept already established connections #new
      iptables:
        chain: INPUT
        match: state
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

    - name: Allow SSH
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        match: state
        ctstate: NEW
        jump: ACCEPT

    # - name: Allow SSH
    #   ansible.builtin.iptables:
    #     chain: OUTPUT
    #     protocol: tcp
    #     destination_port: 22
    #     match: state
    #     ctstate: NEW
    #     jump: ACCEPT
   
    - name: Allow rules for specific ports
      ansible.builtin.iptables:
        chain: INPUT
        protocol: "{{ item.proto }}"
        destination_port: "{{ item.port }}"
        jump: ACCEPT
      loop:
        - { port: "53", proto: "tcp" }
        - { port: "53", proto: "udp" }
        - { port: "80", proto: "tcp" }
        - { port: "443", proto: "tcp" }

    # - name: Allow rules for specific ports
    #   ansible.builtin.iptables:
    #     chain: OUTPUT
    #     protocol: "{{ item.proto }}"
    #     destination_port: "{{ item.port }}"
    #     jump: ACCEPT
    #   loop:
    #     - { port: "53", proto: "tcp" }
    #     - { port: "53", proto: "udp" }
    #     - { port: "80", proto: "tcp" }
    #     - { port: "443", proto: "tcp" }

    - name: Allow all traffic on the loopback interface for INPUT chain
      iptables:
        chain: INPUT
        in_interface: lo
        jump: ACCEPT

    - name: Allow all outgoing traffic on the loopback interface for OUTPUT chain
      iptables:
        chain: OUTPUT
        out_interface: lo
        jump: ACCEPT

    - name: Drop all traffic to loopback addresses not coming from loopback interface
      iptables:
        chain: INPUT
        source: 127.0.0.0/8
        jump: DROP

    - name: Accept incoming established specific protocols
      ansible.builtin.iptables:
        chain: INPUT
        protocol: "{{ item }}"
        match: state
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
      loop:
        - tcp
        - udp
        - icmp

    - name: Set default policies to DROP
      iptables:
        chain: '{{ item }}'
        policy: DROP
        table: filter
      with_items: 
        - INPUT
        - FORWARD
        #- OUTPUT
    
    - name: Allow established IPv6 connections
      ansible.builtin.iptables:
        chain: INPUT
        ctstate:
          - ESTABLISHED
          - RELATED
        jump: ACCEPT
        ip_version: ipv6
  
    - name: Allow incoming SSH on IPv6
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        ctstate: NEW
        syn: match
        jump: ACCEPT
        ip_version: ipv6
    
    - name: Set default policies to DROP for IPv6
      ansible.builtin.iptables:
        chain: "{{ item }}"
        policy: DROP
        table: filter
        ip_version: ipv6
      with_items:
        - INPUT
        - FORWARD
        - OUTPUT
    
    - name: Allow all traffic on loopback interface for INPUT chain (IPv6)
      ansible.builtin.iptables:
        chain: INPUT
        in_interface: lo
        jump: ACCEPT
        ip_version: ipv6
    
    - name: Allow all traffic on loopback interface for OUTPUT chain (IPv6)
      ansible.builtin.iptables:
        chain: OUTPUT
        out_interface: lo
        jump: ACCEPT
        ip_version: ipv6
    
    - name: Drop traffic to loopback addresses not from loopback (IPv6)
      ansible.builtin.iptables:
        chain: INPUT
        source: "::1/128"
        in_interface: "!lo"
        jump: DROP
        ip_version: ipv6
    
    - name: Accept incoming established specific protocol (IPv6)
      ansible.builtin.iptables:
        chain: INPUT
        protocol: "{{ item }}"
        ctstate:
          - ESTABLISHED
        jump: ACCEPT
        ip_version: ipv6
      with_items:
        - tcp
        - udp
        - icmpv6
    
    - name: Allow outgoing specific protocol traffic (IPv6)
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: "{{ item }}"
        ctstate:
          - NEW
          - ESTABLISHED
        jump: ACCEPT
        ip_version: ipv6
      with_items:
        - tcp
        - udp
        - icmpv6
    
    - name: Allow rules for specific ports (IPv6)
      ansible.builtin.iptables:
        chain: INPUT
        protocol: "{{ item.proto }}"
        destination_port: "{{ item.port }}"
        jump: ACCEPT
        ip_version: ipv6
      with_items:
        - { port: "22", proto: "tcp" }
        - { port: "53", proto: "tcp" }
        - { port: "53", proto: "udp" }
        - { port: "80", proto: "tcp" }
        - { port: "443", proto: "tcp" }
      notify: Save iptables rules
