---
- name: Special purpose services
  include_tasks: services.yaml

- name: Tcp Wrapper and System File Permissions
  include_tasks: file_permissions.yaml

- name: Network Configuration Host
  include_tasks: network_configuration_host.yaml

- name: Ensure bogus ICMP responses are ignored
  include_tasks: network_configuration_router.yaml

- name: inetd Services
  include_tasks: apt.yaml

- name: Logging and Auditing
  include_tasks: audit.yaml

- name: Ensure dccp and sctp is disabled
  include_tasks: network_protocol_and_unusedFilesystem.yaml

- name: Filesystem Configuration
  include_tasks: filesystem_configuration.yaml

- name: Ensure filesystem integrity is regularly checked
  include_tasks: aide.yaml
