---
- name: Include CIS Stage Specific vars
  ansible.builtin.include_vars: cis-{{ cis_Stage }}.yaml

- name: Debian related Specification
  ansible.builtin.include_tasks: configure_Debian.yaml
  when:
    ansible_os_family == 'Debian'

- name: CentOS related Specification
  ansible.builtin.include_tasks: configure_RedHat.yaml
  when: ansible_os_family == 'RedHat'
