---
- name: Check the state of SELinux
  command: "getenforce"
  register: selinux_state
  changed_when: false

- debug:
    msg: "{{ selinux_state.stdout }}"

- name: Ensure SETroubleshoot is not installed
  yum:
    name: "{{ item }}"
    state: removed
  when: selinux_state == "Enforcing"
  with_items:
    - mcstrans
    - setroubleshoot
