---
##2.1 Disable Special Purpose Services

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Disable special purpose services if present
  ansible.builtin.systemd:
    name: '{{ item }}'
    enabled: false
    state: stopped
  loop: '{{ os_services_name }}'
  when: item in ansible_facts.services
  ignore_errors: true


- name: Check if postfix config file exists
  stat:
    path: /etc/postfix/main.cf
  register: postfix_main_cf

- name: Set Postfix main.cf for local-only mode
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^inet_interfaces = '
    line: 'inet_interfaces = loopback-only'
  when: postfix_main_cf.stat.exists
  notify: Restart Postfix



# # 2.2 Disable Client Purpose Services
- name: Remove Clients Special Purpose Services
  apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ clients_services_name }}"
