---
- name: Special purpose services should be disabled
  service:
    name: '{{ item }}'
    enabled: false
    state: stopped
    daemon_reload: true
    no_block: false
  with_items:
    - '{{ os_services_name }}'
  ignore_errors: true
