---
# 2.1 Disable Special Purpose Services
- name: Special purpose services should be disabled
  service:
    name: '{{ item }}'
    enabled: false
    state: stopped
    daemon_reload: true
    no_block: false
  with_items:
    - '{{ os_services_name }}'
  ignore_errors: true

- name: Set Postfix main.cf for local-only mode
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^inet_interfaces = '
    line: 'inet_interfaces = loopback-only'
  notify: Restart Postfix
  when: cis_Stage > 1

# 2.2 Disable Client Purpose Services
- name: Remove Clients Special Purpose Services
  apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ clients_services_name }}"
  when: cis_Stage > 1