# 6.1.1.1, 6.1.1.4 Configure journald

# Systemd Journal configuration
- name: Systemd Journal configuration
  when: preferred_logger == "systemd-journald"
  block:
    # 6.1.2.1.1 Ensure systemd-journal-remote is installed
    - name: Ensure systemd-journal-remote is installed
      ansible.builtin.apt:
        name: systemd-journal-remote
        state: present
        update_cache: yes
      when:
        ansible_os_family == 'Debian'

    - name: Ensure systemd-journal-remote is installed
      ansible.builtin.yum:
        name: system-journal-gateway
        state: present
        update_cache: yes
      when:
        ansible_os_family == 'RedHat'

    # 6.1.2.1.4 Ensure systemd-journal-remote service is not in use
    - name: Stop systemd-journal-remote.socket and service
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
      loop:
        - systemd-journal-remote.socket
        - systemd-journal-remote.service
      when: cis_Stage > 1

    - name: Mask systemd-journal-remote.socket and service
      ansible.builtin.systemd:
        name: "{{ item }}"
        masked: yes
      loop:
        - systemd-journal-remote.socket
        - systemd-journal-remote.service
      when: cis_Stage > 1

    # 6.1.2.3 Configure journald log
    - name: Configure journald log rotation settings
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '^#?{{ item.key }}='
        line: '{{ item.key }}={{ item.value }}'
        state: present
      loop:
        - { key: 'SystemMaxUse', value: '500M' }
        - { key: 'SystemKeepFree', value: '100M' }
        - { key: 'RuntimeMaxUse', value: '10M' }
        - { key: 'RuntimeKeepFree', value: '200M' }
        - { key: 'MaxFileSec', value: '1month' }
        - { key: 'ForwardToSyslog', value: 'no' }
        - { key: 'Storage', value: 'persistent' }
        - { key: 'Compress', value: 'yes' }
      notify: Restart systemd-journald

# 6.1.3.4 - Ensure rsyslog log file creation mode is configured

- name: Ensure rsyslog uses restrictive file creation mode
  when: preferred_logger == 'rsyslog'
  block:
    - name: Ensure systemd-journald is configured to forward logs to rsyslog
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '^#?ForwardToSyslog='
        line: 'ForwardToSyslog=yes'
        create: no
        backup: yes
      notify: Restart systemd-journald

    - name: Ensure rsyslog drop-in config directory exists
      ansible.builtin.file:
        path: /etc/rsyslog.d
        state: directory
        mode: '0755'

    - name: Set $FileCreateMode to 0640 in drop-in config
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.d/60-rsyslog.conf
        create: yes
        line: '$FileCreateMode 0640'
        state: present
      notify: Restart rsyslog

    # 6.1.3.7 - Ensure rsyslog is not configured to receive logs from remote clients
    - name: Get rsyslog config files
      ansible.builtin.find:
        paths:
          - /etc/rsyslog.conf
          - /etc/rsyslog.d/
        patterns: '*.conf'
        recurse: no
      register: rsyslog_conf_files
      when: cis_Stage > 1

    - name: Define list of regex patterns to remove
      ansible.builtin.set_fact:
        rsyslog_remove_patterns:
          - '^\\s*module\\s*\\(\\s*load\\s*=\\s*\\"imtcp\\"\\s*\\)'
          - '^\\s*input\\s*\\(\\s*type\\s*=\\s*\\"imtcp\\".*port\\s*=\\s*\\"?514\\"?.*\\)'
          - '^\\s*\\$ModLoad\\s+imtcp'
          - '^\\s*\\$InputTCPServerRun'
      when: cis_Stage > 1

    - name: Remove insecure rsyslog TCP config lines
      ansible.builtin.lineinfile:
        path: "{{ item.0 }}"
        state: absent
        regexp: "{{ item.1 }}"
      loop: "{{ rsyslog_conf_files.files | map(attribute='path') | list | product(rsyslog_remove_patterns) | list }}"
      loop_control:
        label: "{{ item.0 }} => {{ item.1 }}"
      when: cis_Stage > 1

# # # 6.1.4.1 - Ensure access to all logfiles has been configured
- name: Copy log permission check script from template
  ansible.builtin.template:
    src: check_log_permissions.sh.j2
    dest: /usr/local/bin/check_log_permissions.sh
    mode: '0750'
    owner: root
    group: root

- name: Ensure correct permissions and ownership for /var/log files
  ansible.builtin.command: /usr/local/bin/check_log_permissions.sh
  become: true
  register: log_check_result
  changed_when: log_check_result.stdout | length > 0
  failed_when: false
