---
- name: inetd Services
  include_tasks: apt.yaml

- name: Ensure filesystem integrity is regularly checked
  include_tasks: aide_ubuntu.yaml

- name: Secure Boot Settings
  include_tasks: secure_boot_ubuntu.yaml

- name: SELinux Configuration
  include_tasks: selinux_ubuntu.yaml
