---
- name: Reload the services
  service:
    name: '{{ item }}'
    state: restarted
    daemon_reload: true
  with_items:
    - aidecheck.timer
    - aidecheck
    - auditd

- name: Reload systemd units
  systemd:
    daemon_reload: yes